#ifndef RFIDINTERFACE_GLOBAL_H
#define RFIDINTERFACE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(RFIDINTERFACE_LIBRARY)
#  define RFIDINTERFACE_EXPORT Q_DECL_EXPORT
#else
#  define RFIDINTERFACE_EXPORT Q_DECL_IMPORT
#endif

#endif // RFIDINTERFACE_GLOBAL_H
